services:
  react-app:
    container_name: chronos-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
